<header class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
    <div class="navbar-header">
        <p class='admin-fonte navbar-brand'>Admin</p>
    </div>
    <nav class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-left">
            <li><a href='/Admin'>Home</a></li>
            <li><a href='/Artigos'>Artigos</a></li>
            <li><a href="">Eventos</a></li>
     </ul>
    </nav>
    </div>


</header>
<div class="container-fluid">

<p class="fonte-saudacao">BlogRetro</p>
<form action="/Autenticacao/fechar" method="post">
             <button type="submit" class='btn btn-danger'><i class="fa fa-times"></i> Sair</button>

</form>

        <?php  // unset($_SESSION['login'], $_SESSION['senha']); ?>

