<header class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
    <div class="navbar-header">
        <p class='admin-fonte navbar-brand'>Admin</p>
    </div>
    <nav class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-left">
            <li><a href='/Admin_Artigos'>Artigos</a></li>
            <li><a href="">Eventos</a></li>
     </ul>
    </nav>
    </div>


</header>
<div class="container-fluid">

<p class="fonte-saudacao">BlogRetro</p>

        <?php  unset($_SESSION['login'], $_SESSION['senha']); ?>

