<header class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
    <div class="navbar-header">
        <p class='admin-fonte navbar-brand'>Admin</p>
    </div>
    <nav class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-left">
            <li><a href='/Admin'>Home</a></li>
            <li><a href='/Artigos'>Artigos</a></li>
            <li><a href="">Eventos</a></li>
     </ul>
    </nav>
    </div>


</header>
<h2>Inclusão de Artigos</h2>
<div class="container-fluid">
<div class="center-block container-central" >
    <form  enctype="multpart/form-data" method="post" action="/Artigos/salvar">

        <div class="form-group">
                <label for="titulo">Titulo</label>
                <input class="form-control" type="text" name="titulo" id="titulo" value="<?php echo (isset($titulo)) ? $titulo : '' ?>">
        </div>
        <div class="form-group">
                <label for="conteudo">Texto</label>
                <textarea class="form-control" name="conteudo" id="conteudo" cols="30" rows="10" ><?php echo (isset($conteudo) ) ? $conteudo : '' ?></textarea>
        </div>
        <div class="form-group" id='seleciona_categoria'>
                <label for='categoria'>Categoria</label> <a  class='linkcego' id='nova_categoria_link'>Incluir Nova Categoria</a>

            <span class='form-group input-group' id='inclui_nova_categoria' style='display: none'>
                <input class="form-control" type="text" id='novacategoria' data-url='/categoria/nova/nome'>
                    <span class='input-group-addon' style='padding: 0'>
                            <button type="button"  class=' btn btn-sm btn-warning ' id='btnIncluiCategoria'><span class='fa fa-plus-circle'></span></button>
                    </span>
            </span>

                <select class="form-control" name="categoria" id="categoria">
                    <option value='1' selected>Selecione uma categoria</option>
                </select>
        </div>

                <button type="submit" class="btn btn-danger">Salvar</button>
                <input type="hidden" name='id' value="<?php echo ((isset($id)) ? $id : '') ?>">
    </form>


</div>