<!-- Inicio do footer-->   
</div>
<!-- ENDS MAIN -->

<footer>

    <!-- twitter -->
    <div id="twitter-holder">
        <div class="ribbon-left"></div>
        <div class="ribbon">
            <div id="tweets-bar" class="tweet"></div>
        </div>
        <div class="ribbon-right"></div>
    </div>
    <!-- ENDS twitter -->


    <!-- widgets -->
    <ul  class="widget-cols cf">
        <li class="first-col">

            <div class="widget-block">
                <h4>RECENT POSTS</h4>
                <div class="recent-post cf">
                    <a href="#" class="thumb"><img src="img/dummies/54x54.gif" alt="Post" /></a>
                    <div class="post-head">
                        <a href="#">Pellentesque habitant morbi senectus </a><span> March 12, 2011</span>
                    </div>
                </div>
                <div class="recent-post cf">
                    <a href="#" class="thumb"><img src="img/dummies/54x54b.gif" alt="Post" /></a>
                    <div class="post-head">
                        <a href="#">Pellentesque habitant morbi senectus</a><span> March 12, 2011</span>
                    </div>
                </div>
                <div class="recent-post cf">
                    <a href="#" class="thumb"><img src="img/dummies/54x54c.gif" alt="Post" /></a>
                    <div class="post-head">
                        <a href="#">Pellentesque habitant morbi senectus</a><span> March 12, 2011</span>
                    </div>
                </div>
            </div>
        </li>

        <li class="second-col">

            <div class="widget-block">
                <h4>ABOUT</h4>
                <p>Vintage Template it's completely free this means you don't have to pay anything <a href="http://luiszuno.com/blog/license" >read license</a>.</p> 

                <p>Placeholder images by <a href="http://twistedfork.me/" >Dan Matutina</a></p>
                <p>Visit <a href="http://templatecreme.com/" >Template Creme</a> and find the most beautiful free templates up to date.</p>
            </div>

        </li>

        <li class="third-col">

            <div class="widget-block">
                <h4>DUMMY TEXT</h4>
                <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. </p>
            </div>

        </li>

        <li class="fourth-col">

            <div class="widget-block">
                <h4>CATEGORIES</h4>
                <ul>
                    <li class="cat-item"><a href="#" >Design</a></li>
                    <li class="cat-item"><a href="#" >Photo</a></li>
                    <li class="cat-item"><a href="#" >Art</a></li>
                    <li class="cat-item"><a href="#" >Game</a></li>
                    <li class="cat-item"><a href="#" >Film</a></li>
                    <li class="cat-item"><a href="#" >TV</a></li>
                </ul>
            </div>

        </li>	
    </ul>
    <!-- ENDS widgets -->

    <!-- bottom -->
    <div id="bottom">
        <div id="widget-trigger-holder"><a id="widget-trigger" href="#" title="View More" class="poshytip"></a></div>
        <div id="content">HalfTone Theme by <a href="http://www.luiszuno.com" >luiszuno.com</a> </div>
    </div>
    <!-- ENDS bottom -->

</footer>


</div>
<!-- ENDS WRAPPER -->

<!-- JavaScript at the bottom for fast page loading -->

<!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="js/jquery-1.7.1.min.js"><\/script>')</script>

<!-- scripts concatenated and minified via build script -->
<script src="js/custom.js"></script>

<!-- superfish -->
<script  src="js/superfish-1.4.8/js/hoverIntent.js"></script>
<script  src="js/superfish-1.4.8/js/superfish.js"></script>
<script  src="js/superfish-1.4.8/js/supersubs.js"></script>
<!-- ENDS superfish -->

<script src="js/tweet/jquery.tweet.js" ></script>
<script src="js/jquery.isotope.min.js"></script>
<script src="js/jquery.nivo.slider.js" ></script>
<script src="js/css3-mediaqueries.js"></script>
<script src="js/tabs.js"></script>
<script  src="js/poshytip-1.1/src/jquery.poshytip.min.js"></script>
<!-- end scripts -->

</body>
</html>
