<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">

        <title>HalfTone Template</title>
        <meta name="description" content="">

        <!-- Mobile viewport optimized: h5bp.com/viewport -->
        <meta name="viewport" content="width=device-width">


        <link rel="stylesheet" media="screen" href="css/superfish.css" />
        <link rel="stylesheet" href="css/nivo-slider.css" media="all"  />
        <link rel="stylesheet" href="css/tweet.css" media="all"  />
        <link rel="stylesheet" href="css/style.css">
        <link rel="stylesheet" media="all" href="css/lessframework.css"/>


        <!-- All JavaScript at the bottom, except this Modernizr build.
           Modernizr enables HTML5 elements & feature detects for optimal performance.
           Create your own custom Modernizr build: www.modernizr.com/download/ -->
        <script src="js/modernizr-2.5.3.min.js"></script>
    </head>
    <body>

        <!-- WRAPPER -->
        <div class="wrapper cf">
            <header class="cf">

                <!-- social-bar -->
                <div id="social-bar-holder">
                    <ul id="social-bar" class="cf">

                        <li class="dribbble"><a href="http://www.dribbble.com/ansimuz"  title="Dribbble" ></a></li>
                        <li class="facebook"><a href="http://www.facebook.com/pages/Ansimuz/224538697564461"  title="Facebook" ></a></li>
                        <li class="forrst"><a href="http://forrst.me/ansimuz"  title="forrst" ></a></li>
                        <li class="googleplus"><a href="https://plus.google.com/109030791898417339180/posts"  title="googleplus" ></a></li>
                        <li class="twitter"><a href="https://twitter.com/ansimuz"  title="twitter" ></a></li>
                    </ul>
                </div>
                <div class="cf"></div>
                <!-- ENDS social-bar -->

                <div id="logo" class="cf">
                    <a href="index.html" ><img src="img/logo.png" alt="" /></a>
                </div>

                <!-- nav -->
                <nav class="cf">
                    <ul id="nav" class="sf-menu">
                        <li class="current-menu-item"><a href="index.html"><span>HOME</span></a></li>
                        <li><a href="page.html"><span>FEATURES</span></a>
                            <ul>
                                <li><a href="page.html">Columns</a></li>
                                <li><a href="page-typography.html">Typography</a></li>
                                <li><a href="page-elements.html">Elements</a></li>
                                <li><a href="page-sidebar.html">Sidebar Page</a></li>
                            </ul>
                        </li>
                        <li><a href="blog.html"><span>BLOG</span></a></li>
                        <li><a href="portfolio.html"><span>WORK</span></a></li>
                        <li><a href="contact.html"><span>CONTACT</span></a></li>
                        <li><a href="http://themeforest.net/item/halftone-wordpress-theme/2661175?ref=Ansimuz"><span>WORDPRESS VERSION</span></a></li>
                    </ul>
                    <div id="combo-holder"></div>
                </nav>
                <!-- ends nav -->

            </header>

            <div role="main" id="main" class="cf">

                <!-- ENDS SLIDER  Corta para o cabeçalio-->

