<div class="container-fluid">

        <form class="form-signin" method="post" id='form-login' >
        <?php foreach($view_mensagem as $classe => $texto) : ?>
        <div class='alert <?php echo $classe?>'><?php echo $texto ?></div>
        <?php endforeach;?>
        <h2 class="form-signin-heading" id='tit-login'>Login</h2>
        <label for="inputEmail" class="sr-only"></label>
        <input type="email" id="inputEmail" name='email' class="form-control" placeholder="Digite seu E-mail" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" name="senha" class="form-control" placeholder="Senha" required>
        <label for="confirmSenha" class="sr-only">Confime Senha</label>
        <input type="password" id="confirmPassword" name="confirmaSenha" class="form-control esconde" placeholder="Confirme a Senha">
        <div class="checkbox">
          <label>
            <input type="checkbox" value="Lembre-me"> Lembrar Minha Senha
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
        <span class="btn btn-lg btn-success btn-block" id='cad'>Cadastrar Usuário</span>
      </form>
