<header class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <p class='admin-fonte navbar-brand'>Admin</p>
        </div>
        <nav class="navbar-collapse collapse pull-left">
            <ul class="nav navbar-nav navbar-left">
                <li><a href='/Admin'>Home</a></li>
                <li><a href='/Artigos'>Artigos</a></li>
                <li><a href="/Usuario">Usuários</a></li>
            </ul>
        </nav>
        <form action="/Autenticacao/fechar" method="post" style="padding: 15px">
            <button type="submit" class='btn btn-danger pull-right'><i class="fa fa-times"></i> Sair</button>
        </form>
    </div>
</header>


