<section class="container-fluid">
<h2 class='page-header text-center bg-primary'>Usuarios</h2>
<table class="table table-striped table-hover">
    <thead>
        <tr>
        <th>Nome</th>
        <th>E-mail</th>
        <th>Perfil</th>
        <th colspan="2">Controle</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($view_usuarios as $usuario) : extract($usuario);?>
        <tr>
            <td><?php echo $nome ?></td>
            <td><?php echo $email ?></td>
            <td><?php echo $perfil_nome ?></td>
            <td>
                <form>
                    <button class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></span> Editar</button>
                    <input type="hidden" value="<?php echo $id; ?>" name='id'>
                </form>
            </td>
            <td>
                <form>
                    <button class="btn btn-danger" ><span class="glyphicon glyphicon-trash" ></span> Excluir</button>
                    <input type="hidden" value="<?php echo $id; ?>" name='id'>
                </form>
            </td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>
</section>