CREATE TABLE `artigos` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`imagem` VARCHAR(200) NOT NULL,
	`link` VARCHAR(200) NULL DEFAULT NULL,
	`titulo` VARCHAR(200) NULL DEFAULT NULL,
	`autor` VARCHAR(100) NULL DEFAULT NULL,
	`conteudo` LONGTEXT NULL,
	`categoria` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;

CREATE TABLE `categoria` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nome` VARCHAR(100) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;

CREATE TABLE `usuarios` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(100) NULL DEFAULT NULL,
	`senha` VARCHAR(15) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=16
;
